### ISSUE TITLE
TimeZoneがセットされない

### ISSUE THREAD

**Issue by miyuk** [l3tnun/docker-mirakurun-epgstation#1]
## Issue
Docker-Composeで立ち上げた際に`epgstation`と`mirakurun`の時間がタイムゾーン指定されていないためWeb画面で表示した際の番組表表示がおかしくなっている

Nodeでは、環境変数`TZ`でタイムゾーンを確認しているため/etc/localtimeでは不十分

docker-compose logs抜粋
```
epgstation    | [2019-03-23T13:44:53.869] [INFO] system - wait mirakurun
mirakurun     | 2019-03-23T13:44:57.284+00:00 info: load config `/usr/local/etc/mirakurun/server.yml`
mysql         | 2019-03-23 22:44:53 0 [Note] mysqld (mysqld 10.3.13-MariaDB-1:10.3.13+maria~bionic) starting as process 1 ...
```
## Resolution
`epgstation`と`mirakurun`の環境変数に`TZ: Asia/Tokyo`を追加

こちらの環境で確認出来次第PR投げます

**Comment by l3tnun** [comment]
プルリクありがとうございます。
マージしました。
