### ISSUE TITLE
ffmpegのインストール

### ISSUE THREAD

**Issue by 5ym** [l3tnun/docker-mirakurun-epgstation#11]
環境更新の度ビルドに時間がかなりかかっているのでdebianのデフォルトリポジトリのffmpegを利用したいのですが、何か環境依存や合理的な理由でローカルビルド版をつかわなければならない理由などありますでしょうか。
お手数ですが回答のほどよろしくお願いいたします。

**Comment by 5ym** [comment]
こんな感じです
https://github.com/5ym/docker-mirakurun-epgstation/blob/master/epgstation/Dockerfile

**Comment by l3tnun** [comment]
各種パッチを当てたり、必要なものを組み込んだりするためですね。
vaapi対応やqsv対応など。
また [0p1pp1/FFmpeg](https://github.com/0p1pp1/FFmpeg) 等の派生版を使用したりもできますしね。

要は標準の ffmpeg では不十分な部分があるためです。

環境に応じてパッケージをインストールしても良いですし、ビルドしても良いです。
故に現状はソースからビルドするようにしています。

**Comment by 5ym** [comment]
なるほど確かにtsを扱う上ではプラグインの想定などは必要ですねありがとうございます。
とりあえずは効果はあるかわかりませんがmakeのjob数を増やしてビルド高速化してみます
