### ISSUE TITLE
ローカルに作成した旧環境(PM2使用)のデータベースを、新環境(Docker仕様)へのレストアについて

### ISSUE THREAD

**Issue by shirow-github** [l3tnun/docker-mirakurun-epgstation#14]
旧環境
OS：Vine Linux Seed x86
node：v12.16.3
PM2：v4.4.0
mirakurun：v3.1.1
epgstation：v1.7.0（sqlite3使用）

新環境（テストのため、VMWare上に構築）
OS：Ubuntu Linux 20.04 LTS x64
node：v14.4.0
PM2：なし
mirakurun：v3.1.1
epgstation：v1.7.0（mariadb使用）

※mirakurun/conf/tuners.ymlを旧環境のmirakurunのIPアドレス指定に修正して、新環境でも番組表が表示できています。

Q：
ローカル環境にて運用していたEPGStationを、新たにインストールし直したDockerを使用した環境へ移行を計画しています。

今まで使用していたEPGStation内にて、npm run backup epgstation.dbとしてバックアップ、

新環境のdocker-mirakurun-epgstation/epgstationにて、npm run restore epgstation.dbをした所、エラーで失敗しました。

'--------------------------------
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /home/docker/docker/docker-mirakurun-epgstation/epgstation/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/home/docker/docker/docker-mirakurun-epgstation/epgstation/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/docker/.npm/_logs/2020-07-08T03_34_57_849Z-debug.log
'--------------------------------

**Comment by l3tnun** [comment]
epgstation のコンテナの中で作業してください。

**Comment by shirow-github** [comment]
ご連絡ありがとうございます。
以下の通り行い、データベースのリストアが出来ました。

`$ sudo docker cp epgstation.db docker-mirakurun-epgstation_epgstation_1:/app`
`$ sudo docker exec -it docker-mirakurun-epgstation_epgstation_1 /bin/bash`
`# npm run restore epgstation.db`
`# exit`

ありがとうございました。
