### ISSUE TITLE
「ルール画面」ルールが０件の際に追加ボタンが表示されない

### ISSUE THREAD

**Issue by teandt** [l3tnun/docker-mirakurun-epgstation#27]
久々にアップデートでDB空から作業して現象に気づきました。

**現象**
ルールが０件の場合、右下に表示される追加のボタンが表示されません。（検索画面に遷移するボタン）
１件でも追加するとボタンが現れ、それを削除すると再び消えます。

**環境**
- Ubuntu 20.04.2 LTS
- docker-mirakurun-epgstation：v2
- Docker version 20.10.5
- docker-compose version 1.27.4

**使用ブラウザ**
- Windows10 Chrome 89.0.4389.90
- Ubuntu Linux 20.04 LTS Firefox 86.0

どちらも同じ挙動となりました。

![image](https://user-images.githubusercontent.com/50020829/112590224-d0172f00-8e45-11eb-9968-b7d142174ddd.png)
![image](https://user-images.githubusercontent.com/50020829/112590254-defde180-8e45-11eb-870a-9d82e173f2cf.png)

**Comment by l3tnun** [comment]
報告ありがとうございます。
あー確かに今の実装だとそうなってますね。
ただ docker-mirakurun-epgstation の問題ではなく、epgstation の問題なので epgstation のリポジトリに issue を立て直してもらえますか？

**Comment by teandt** [comment]
了解です
epgstationの方に立て直します
