### ISSUE TITLE
dockerでインストールした際のdefault derectoryについて

### ISSUE THREAD

**Issue by yo-yo44** [l3tnun/docker-mirakurun-epgstation#35]
よろしくお願いします。

最新のものをdockerでインストール済みです。

以前、tsファイルとエンコードしたファイルを分けられる
default ts derectory
default encoded derectory
というオプションがあったのですが、docker版をインストールしてから、録画後に分別されていません。このオプションは省略されましたか。

**Comment by l3tnun** [comment]
お返事が遅くなってしまって、すいません。

以前のというのは v1 の頃の話を指していますでしょうか？
v2になってからは廃止されました。

あとこの issue の内容ですが、docker に限った話ではないので issue を建てる場所として不適切です。

**Comment by yo-yo44** [comment]
ご回答ありがとうございます。色々試して出来なかったので、納得できました。

質問場所について、不適切なところがあり申し訳ございません。docker版からの変更だと思ってしまい、誤った場所で質問をしてしまいました。今後はepgstatinonの方に記載したいと思います。ありがとうございました。
