### ISSUE TITLE
エンコードが終わらない

### ISSUE THREAD

**Issue by soichiro-oda** [l3tnun/docker-mirakurun-epgstation#36]
お世話になっております。いつも有難く利用させていただいております。

環境

Ubuntu 18.04.6 LTS
docker-mirakurun-epgstation：v2
Docker version 20.10.7
docker-compose version 1.17.1

事象

短時間の録画動画を利用したく、
4チャンネルを並行して30秒間隔で録画しているのですが、
不定期にエンコードが終わらないケースが見られます。

encode.logを見ましたが、以下のようなaddのログ以降、エラーログも何も出力されず原因箇所の特定ができておりません。
[2022-02-16T11:43:31.072] [INFO] encode - add new encode: 106

epgstationのUIでは、キャプチャの画面で停止しておりました。
![キャプチャ_20220216](https://user-images.githubusercontent.com/84898288/154223411-961d199f-0b8b-4992-8ede-f513696f954b.PNG)

**Comment by l3tnun** [comment]
[log-manual.md](https://github.com/l3tnun/EPGStation/blob/988b18b15e86b4f882a12e5fe4a8bc5efda69503/doc/log-manual.md)こちらを確認してご自身で調査してください。
