### ISSUE TITLE
EPGstationのコンテナだけnpmエラーで停止

### ISSUE THREAD

**Issue by lkin** [l3tnun/docker-mirakurun-epgstation#4]
お世話になっております！この度マニュアルインストールしてみたら、EPGstationのコンテナだけ”/bin/sh: 1: npm: not found”というエラーで停止します。
mirakurunとmariadbはちゃんと起動しますし、通常のEPGstationはpm2を使って問題なく起動できましたが、録画を予約てもファイルの出力は起こりませんでした。
docker-compose.ymlはホスト側のディレクトリとカードリーダーのデバイス（- /dev/bus/usb/001/004:/dev/bus/usb/001/004）の追加以外は触っていません。
よろしくお願いいたします！

**Comment by l3tnun** [comment]
こちらの環境で確認しますのでしばらくお待ちください。

**Comment by l3tnun** [comment]
確認しました。
特に問題はありませんでした。
おそらくイメージが正しく作成できていないだけだと思いますので、再作成をしてみてください。

epgstation のコンテナで問題があれば、同じ方法で node をインストールしている mirakurun のコンテナでも同じ問題が発生するはずです。
イメージの再作成で解決しない場合は再度 issue を open してください。
