### ISSUE TITLE
【質問】「放映中」や「番組表」が取得できません。

### ISSUE THREAD

**Issue by dailikessushi** [l3tnun/docker-mirakurun-epgstation#40]
使用環境は、
【OS】Linux Mint 21.2 "Victoria" Cinnamon
【TVチューナカード】PLEX PX-Q3PE4
です。

Version 2.6.? のときからお世話になっております。
いつも開発ありがとうございます。

Version 2.6.? のバージョンの更新をしたところ、
動作しなくなってしまったので、
OSごとアップグレードしまして、
また新しく docker-mirakurun-epgstasion を導入させていただきます。

現在、
sudo docker-compose up -d
をして10時間経ったのですが、
依然、「放映中」や「番組表」の内容が表示されないので、困っている次第です。

http://DockerHostIP:8888
にて、
EPGStation v2.7.1
は起動します。

/home/docker/docker-mirakurun-epgstation/mirakurun/conf/channels.yml
は、以前の Version 2.6.? で動作していたファイルを流用いたしました。

$ recpt1 --b25 --strip 27 10 ~/test.ts
using B25...
enable B25 strip
C/N = 34.346776dB
(PID:60309)(CH:T27) Recording...
(PID:60309)(CH:T27) Recorded 10sec
として、録画ができていることも確認いたしました。

FFMPEG もインストール済みです。

他に考えられる欠点がございましたらお教えくださいませ。

**Comment by dailikessushi** [comment]
その後、

/home/docker/docker-mirakurun-epgstation/mirakurun/conf/tuners.yml
も、以前の Version 2.6.? で動作していたファイルを流用してみましたが、
症状に変化がございませんでした。

他に何が問題でしょうか？

**Comment by dicekshin** [comment]
「PLEX PX-Q3PE4 docker-mirakurun-epgstation」でウェブ検索をかけたら、
解決できるウェブページを発見し、それで解決いたしました。
私の検索力がぜんぜん足りなかったようです。

お騒がせしてしまって申し訳ございませんでした。

**Comment by dailikessushi** [comment]
「PLEX PX-Q3PE4 docker-mirakurun-epgstation」でウェブ検索をしたら、
有用なウェブページを発見し、解決いたしました。
私の検索力がぜんぜん足りなかったようです。

お騒がせして大変申し訳ございませんでした。
