### ISSUE TITLE
録画ファイルが目的のディレクトリに保存されません。

### ISSUE THREAD

**Issue by dailikessushi** [l3tnun/docker-mirakurun-epgstation#41]
以前から docker-mirakurun-epgstaion には大変お世話になっております。

インストールに手こずりましたが、何とか視聴・録画できるようになりました。

そこで、録画先にあるディレクトリを指定したのですが、思い通りにそのディレクトリに録画ファイルが保存されません。動画変換はできています。
詳しい設定は以下のようにしました。
```
$ pwd
/home/docker/docker/docker-mirakurun-epgstation
$ cat docker-compose.yml | grep \/home\/share\/Videos\/tv
            - /home/share/Videos/tv/thumbnail:/app/thumbnail
            - /home/share/Videos/tv:/app/recorded
$ cat epgstation/config/config.yml | grep \/home\/share\/Videos\/tv
      path: '/home/share/Videos/tv'
thumbnail: '/home/share/Videos/tv/thumbnail'
$ 
```
このように設定して起動して録画しても、/home/share/Videos/tv 以下に保存されず、
起動SSDのLinux領域のどこかに保存されてしまうのです。
`$ sudo find / -name '*番組タイトルの一部*'`
としても、どこにも録画済みファイルが見当たらないです。

ちなみに、EPGStation v2.7.1 の[設定]の[ストレージ]を見ると、起動SSDのLinux領域の容量が表示されます。
これでは内蔵大容量HDDに保存できません。この内蔵HDDは確かにmountされています。当該ディレクトリも閲覧でき、パーミッションも777です。

以前の バージョン2.6.? ではこの設定で問題ありませんでした。
どうか解決のヒントをくださいませ。

**Comment by vonvonhero** [comment]
>$ cat epgstation/config/config.yml | grep \/home\/share\/Videos\/tv
>      path: '/home/share/Videos/tv'
上記はどこのpathでしょうか？

これが、recorded: セクション内のpathである場合、
コンテナ内での録画先をデフォルトの/app/recordedで使うのであれば、
epgstation/config/config.yml　でrecorded pathをホストの録画先(/home/share/Videos/tv)に変更する必要はないのではないでしょうか？
config.ymlに記載するpathはコンテナ内のpathです。
今回のケースで言えば、特にデフォルトから変更する必要が無いように思います。

https://github.com/l3tnun/docker-mirakurun-epgstation/blob/d8be751a476cf795a8e939e71fe914f492db7d21/epgstation/config/config.yml.template#L25-L29

**Comment by dailikessushi** [comment]
おっしゃるとおり、epgstation/config/config.yml の変更は必要ありませんでした。
大変お騒がせいたしました。
