### ISSUE TITLE
ストレージ情報取得失敗問題

### ISSUE THREAD

**Issue by hsnuhayato** [l3tnun/docker-mirakurun-epgstation#42]
何回も同じ問題で騒がして申し訳ございません。
現在こちらのレポジトリのdocker-compose.yml使わせて頂いていますが、
dockerfile見たら
l3tnun/epgstation:master-debian
このバージョンのepgstationが使われているようです。
こちらのバージョンのepgstationが使用しているdiskusage-ng のバージョンが1.0.1でしょうか？

ちなみに。ストレージ情報取得は失敗しているが、録画はできています。

よろしくお願いいたします。

**Comment by l3tnun** [comment]
epgstationの問題ですので、そもそもissueを立てる場所が違います。
ご自身で調べてください。
