### ISSUE TITLE
EPGStation v2のHTTPサーバーが起動しません

### ISSUE THREAD

**Issue by rasumus** [l3tnun/docker-mirakurun-epgstation#43]
EPGStation v2で8888ポートにアクセスできません。
Firefoxブラウザでアクセスすると「正常に接続できませんでした。192.168.64.13:8888 のサーバーへの接続を確立できませんでした。このサイトが一時的に利用できなくなっていたり、サーバーの負荷が高すぎて接続できなくなっている可能性があります。しばらくしてから再度試してください」となります。
起動時のメッセージとEPGStationのconfig.ymlは下記です。
何度か入れ直しましたが変わりません。
MirakurunコンテナとMysqlコンテナは稼働しています。
Mirakurunにはブラウザでアクセスでき、チューナー設定・チャンネル設定は正しく表示されています。
御助言頂ければ助かります。
Windows 11上のVMPlayer仮想マシンのXubuntu 22.04にインストールしています。

（起動時メッセージ）
$ docker-compose up
epgstation-v2.6.20 | > epgstation@2.7.3 start
epgstation-v2.6.20 | > node dist/index.js
epgstation-v2.6.20 |
mirakurun-3.9.0-rc.4 | 2023-12-29T18:09:54.734+09:00 info: load server config `/app-config/server.yml`
mirakurun-3.9.0-rc.4 | 2023-12-29T18:09:54.744+09:00 info: load server config (merged w/ env): {"logLevel":2,"path":"/var/run/mirakurun.sock","port":40772,"allowIPv4CidrRanges":["10.0.0.0/8","127.0.0.0/8","172.16.0.0/12","192.168.0.0/16"],"allowIPv6CidrRanges":["fc00::/7"],"disableIPv6":true,"hostname":"32fd7533fe6c"}
mirakurun-3.9.0-rc.4 | 2023-12-29T18:09:54.760+09:00 info: load channels config `/app-config/channels.yml`
mirakurun-3.9.0-rc.4 | 2023-12-29T18:09:54.780+09:00 info: load tuners config `/app-config/tuners.yml`
mirakurun-3.9.0-rc.4 | 2023-12-29T18:09:54.785+09:00 info: 4 of 4 tuners loaded
mirakurun-3.9.0-rc.4 | 2023-12-29T18:09:54.798+09:00 info: load db `/app-data/services.json` w/ integrity (azx4yAyUoqa9Os9g1+VoAtVMYFdFKrFKeu84E/tl54M=)
mirakurun-3.9.0-rc.4 | 2023-12-29T18:09:54.806+09:00 info: load db `/app-data/programs.json` w/ integrity (azx4yAyUoqa9Os9g1+VoAtVMYFdFKrFKeu84E/tl54M=)
mirakurun-3.9.0-rc.4 | 2023-12-29T18:09:57.672+09:00 info: RPC interface is enabled
mirakurun-3.9.0-rc.4 | 2023-12-29T18:09:57.677+09:00 info: listening on http+unix://%2Fvar%2Frun%2Fmirakurun.sock
mirakurun-3.9.0-rc.4 | 2023-12-29T18:09:57.678+09:00 info: listening on http://172.29.0.2:40772
mirakurun-3.9.0-rc.4 | 2023-12-29T18:09:57.680+09:00 info: listening on http://127.0.0.1:40772
mirakurun-3.9.0-rc.4 | 2023-12-29T18:09:57.806+09:00 info: save db `/app-data/services.json` w/ integirty (azx4yAyUoqa9Os9g1+VoAtVMYFdFKrFKeu84E/tl54M=)
epgstation-v2.6.20 | [2023-12-29T18:09:59.278] [INFO] system - config.yml read success
epgstation-v2.6.20 | [2023-12-29T18:09:59.307] [INFO] system - check mirakurun

（config.yml抜粋）
port: 8888
mirakurunPath: 'http://l92.168.64.13:40772'
以下データベース設定などに続く。
以上

**Comment by tobitti0** [comment]
`mirakurunPath:http://l92.168.64.13:40772`
MirakurunPath のアドレスが1（イチ）92ではなくl(エル)92になっているのが気になります。
（直接的な問題点かどうかはわかりません。）

**Comment by rasumus** [comment]
tobitti0様、ご指摘ありがとうございます。
このアドレスの部分をlocalhostに変更したりした中で間違ったものになっていたようです。
改めてmirakurunPathを '192.168.64.13:40772' 'localhost:40772' '127.0.0.1:40772' に書き換えてやってみましたが、いずれもブラウザからEPGStationにアクセスできませんでした。

**Comment by ouvill** [comment]
@rasumus 

`epgstation/config/config.yml`の`mirakurunPath:http:**********`のところですが、書き換えずに以下のままで大丈夫です。

```yml
mirakurunPath: http://mirakurun:40772/
```

**Comment by l3tnun** [comment]
EPGStationの問題ではなく、ネットワークの問題のようですので閉じます。
