### ISSUE TITLE
【質問】docker環境における録画失敗のトラブルシューティングについて

### ISSUE THREAD

**Issue by tokohito** [l3tnun/docker-mirakurun-epgstation#7]
### 環境
* Version of EPGStation: `1.6.1`
* Version of Mirakurun: `2.13.0`
* Version of Node: `v8.9.4`
* Version of NPM: `不明`
* OS: Debian stretch(docker) on Ubuntu 18.04
* Architecture: x64

### Issue
たまに録画が失敗するようになってしまいました。解消したいのでアドバイスをお願いします。

▼症状
・録画中の番組が途中で分断され、2～3つのファイルに分割して保存される
・別チャンネルを並行で録画している場合、大体同じタイミングで症状が発生していることが多いが絶対に同じではない
　(チャンネルAが3分割されて、裏録のチャンネルBは2分割で済んでいるケースもあり)
・分割された各ファイルに対してrecordedEndCommandはそれぞれ実行されるが、program IDなどは
　最初のファイルに対してしか適用されない
・問題が発生して以降の録画予約すべてこでこの症状が発生するようなことはなく、現状では発生は偶発的

▼質問
1. mirakurunログについて
症状から推察するにEPGStationの問題ではなくどちらかというとMirakurun側のような気がしますが、./mirakurun/以下にログのディレクトリが無く、docker shellでmirakurun logコマンドを実行してもログは出力されませんでした。docker環境でのmirakurunログの取得の仕方はどうすればよろしいでしょうか

2. epgstationログ抑止について
定義しているルール数が多いせいで、"system - start update rule:"のログが大量に吐かれてしまい、epgstation systemログの視認性が悪くなる＆過去のログがあっという間に流れてしまいます。上記のイベントだけ抑止する、もしくは総件数のサマリーログだけの出力に留めるなどの方法はありませんか？

以上、よろしくお願いいたします。

**Comment by l3tnun** [comment]
録画が分割する原因は分かりませんが候補を上げるなら

- 録画保存先のストレージが耐えられず死んでいる or 切断されている
- Mirakurun との接続が何らかの理由で切れてる
- Mirakurun 側の不調によりストリームが切断されている

nasなどのネットワーク越しに録画を保存していたりしませんか?

1. について
標準出力に吐き出しているので ```docker logs コンテナID``` で出ます

2. について
[conf-manual.md](https://github.com/l3tnun/EPGStation/blob/master/doc/conf-manual.md#%E4%BA%88%E7%B4%84%E6%83%85%E5%A0%B1%E6%9B%B4%E6%96%B0%E6%99%82%E3%81%AE%E3%83%AD%E3%82%B0%E5%87%BA%E5%8A%9B%E3%82%92%E6%8A%91%E3%81%88%E3%82%8B%E3%81%8B) を読みましょう

**Comment by tokohito** [comment]
コメントありがとうございます。

＞標準出力に吐き出しているので docker logs コンテナID で出ます
ちゃんと過去の分も遡ってみれました。ありがとうございます。

＞conf-manual.md を読みましょう
見落としてました、すいません。

＞nasなどのネットワーク越しに録画を保存していたりしませんか?
nasではなくローカルストレージなのですが、RAIDボリューム(正確にはZFS)なのでその辺も影響あるかもしれません。

ただmirakurunログに↓がかなり出力されていたので、並列度が高すぎるのが問題かもしれません。まずはバッファを増やして様子を見たいと思います。
>2020-02-06T00:18:31.526+09:00 warn: TSFilter is overflowing the buffer...

**Comment by tokohito** [comment]
Mirakurunのバッファとヒープサイズを拡張しても症状が出てしまったのですが、
よくよく観察すると、同じタイミングにEPGStationの書き込み先と同じZFSプールを
利用しているコピー処理がdisk IOを過剰に使ってしまっているせいでした。

コピー処理が走るブロックデバイスに対し、QoS制御をかけることで回避できるようになりました。
お騒がせしました。クローズします。
