### ISSUE TITLE
DVBドライバの使用

### ISSUE THREAD

**Issue by 5ym** [l3tnun/docker-mirakurun-epgstation#9]
個人的にやりたいというのがほとんどなのですが、現状PT3はlinuxのほとんどのディストリビューションでDVBドライバがあたるっぽいのでそれを利用するようにすれば本体側のセットアップがほとんど不要で利用できるようになると思います。
おそらくaptだったら`dvb-tools`などをインストールすれば使用できるはずです

**Comment by 5ym** [comment]
参考URL
https://honeycome.net/archives/672

**Comment by l3tnun** [comment]
もし対応するとしたら、Mirakurun 公式の docker 対応を待ってからですね。

https://twitter.com/Chinachu_REC/status/1257852888270823431

**Comment by 5ym** [comment]
コメントありがとうございます。そういえば対応するみたいですね。
